stages:
  - 🐍 lint
  - 🤞 test
  - 📦 build
  - 🚀 deploy

variables:
  PYTHON_DOCKER_IMAGE: python:3.12-slim-bookworm
  SFCGAL_REGISTRY: registry.gitlab.com/sfcgal/sfcgal

lint:flake8:
  stage: 🐍 lint
  image: ${PYTHON_DOCKER_IMAGE}
  only:
    refs:
      - merge_requests
      - master
    changes:
      - "cookbook/*.py"
      - "pysfcgal/**/*.py"
      - "tests/**/*.{py,wkt}"
      - ".gitlab-ci.yml"
      - "scripts/*.py"
  before_script:
    - python -m pip install --force-reinstall flake8==7.3.0
  script:
    - flake8 scripts/*.py pysfcgal/ tests/ --config=setup.cfg

lint:commit:
  stage: 🐍 lint
  image: ${PYTHON_DOCKER_IMAGE}
  before_script:
    - apt-get update && apt-get install -y git
    - pip install commitizen==4.6.3
  script:
    - cz check --rev-range $CI_MERGE_REQUEST_DIFF_BASE_SHA..HEAD
  only:
    refs:
      - merge_requests

lint:mypy:
  stage: 🐍 lint
  image: ${PYTHON_DOCKER_IMAGE}
  only:
    refs:
      - merge_requests
      - master
    changes:
      - "cookbook/*.py"
      - "pysfcgal/**/*.py"
      - ".gitlab-ci.yml"
      - "scripts/*.py"
  before_script:
    - python -m pip install -U mypy types-cffi typing-extensions
  script:
    - mypy scripts/*.py pysfcgal/

test:unit:
  stage: 🤞 test
  image: ${SFCGAL_REGISTRY}:debian-latest
  only:
    refs:
      - merge_requests
      - master
    changes:
      - "pysfcgal/*.py"
      - "pysfcgal/*.c"
      - "tests/**/*.py"
      - ".gitlab-ci.yml"
  before_script:
    - apt install --no-install-recommends --yes python3 python3-pip python3-dev python3-venv gcc
    - python3 -m venv venv
    - source venv/bin/activate
    - python3 -m pip install -U pytest pytest-cov
    - pip install -e .
    - python3 -m pip install icontract
  script:
    - pytest  -vv --junitxml=junit/test-results-unit.xml --cov pysfcgal --cov-report=xml:coverage-reports/coverage-unit.xml
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage-reports/coverage-unit.xml
      junit:
        - junit/test-results-unit.xml

test:cookbook:
  stage: 🤞 test
  image: ${SFCGAL_REGISTRY}:debian-latest
  only:
    refs:
      - merge_requests
      - master
    changes:
      - "cookbook/*.py"
  before_script:
    # use conda to easily install gdal
    # install conda
    - apt install --no-install-recommends --yes ca-certificates gcc wget
    - wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O /tmp/miniforge.sh
    - bash /tmp/miniforge.sh -b -p /opt/conda
    - /opt/conda/bin/conda init bash
    # activate conda
    - source /opt/conda/etc/profile.d/conda.sh
    # create env with conda
    - conda create -n venv -y -c conda-forge python=3.11 gdal
    - conda activate venv
    - pip install -e .
  script:
    - source /opt/conda/etc/profile.d/conda.sh
    - conda activate venv
    - for file in ./cookbook/*.py; do python3 "$file"; done

build:windows-osgeo4w-wheel:
  stage: 📦 build
  tags:
    - saas-windows-medium-amd64
  rules:
    # on default branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: always
      variables:
        SFCGAL_VERSION: "latest"
    # on a tag
    - if: $CI_COMMIT_TAG
      when: always
      variables:
        SFCGAL_VERSION: "$CI_COMMIT_TAG"
    # on a MR if previous jobs are successful
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      variables:
        SFCGAL_VERSION: "latest"
      allow_failure: true
  artifacts:
    paths:
      - dist_windows
  before_script:
    - Start-Service -Name "docker"
    - docker login -u $env:CI_REGISTRY_USER -p $env:CI_REGISTRY_PASSWORD $env:CI_REGISTRY
  script:
    - |
      $dir = $pwd
      if ($env:CI_COMMIT_TAG) {
        $dev_version = 0
      } else {
        $dev_version = 1
      }
      docker run `
        --rm `
        --mount type=bind,source=$dir,target=c:\pysfcgal `
        --workdir "c:\pysfcgal" `
        $env:SFCGAL_REGISTRY":windows-$env:SFCGAL_VERSION" `
        powershell -Command ".\ci\build.ps1 -DEVEL_VERSION $dev_version -DEVEL_DATE $env:CI_COMMIT_TIMESTAMP"

build:linux-wheel-python:
  stage: 📦 build
  image: docker:27.3
  services:
    - docker:27.3-dind
  rules:
    # on default branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        SFCGAL_VERSION: "latest"
      when: always
    # on a tag
    - if: $CI_COMMIT_TAG
      variables:
        SFCGAL_VERSION: "$CI_COMMIT_TAG"
      when: always
    # on a MR if previous jobs are successful
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        SFCGAL_VERSION: "latest"
      when: manual
      allow_failure: true
  variables:
    SFCGAL_REGISTRY: registry.gitlab.com/sfcgal/sfcgal
  parallel:
    matrix:
      - PYTHON_VERSION: ['3.10', '3.11', '3.12', '3.13', '3.14']
  script:
    - |
      if [ -z "$CI_COMMIT_TAG" ]; then
        DEVEL_VERSION=true
      else
        DEVEL_VERSION=false
      fi
    - docker build
      --tag build_linux_wheel
      --build-arg="DEVEL_DATE=${CI_COMMIT_TIMESTAMP}"
      --build-arg="DEVEL_VERSION=${DEVEL_VERSION}"
      --build-arg="SFCGAL_REGISTRY=${SFCGAL_REGISTRY}"
      --build-arg="SFCGAL_VERSION=${SFCGAL_VERSION}"
      --build-arg="PYTHON_WHEEL_VERSION=${PYTHON_VERSION}"
      -f "docker/Dockerfile_linux_wheel"
      .
    - CONTAINER_ID=$(docker run -d -t build_linux_wheel)
    - docker cp ${CONTAINER_ID}:/dist_linux_${PYTHON_VERSION}/ ./
    - docker stop ${CONTAINER_ID}
  artifacts:
    paths:
      - dist_linux_$PYTHON_VERSION

build:macos-wheel-python:
  stage: 📦 build
  tags:
    - saas-macos-large-m2pro
  image: macos-15-xcode-16
  variables:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_UPGRADE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  rules:
    # on default branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: always
    # on a tag
    - if: $CI_COMMIT_TAG
      when: always
    # on a MR if previous jobs are successful
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
  parallel:
    matrix:
      - PYTHON_VERSION: ['3.10', '3.11', '3.12', '3.13', '3.14']
  script:
    - |
      if [ -z "$CI_COMMIT_TAG" ]; then
        DEVEL_VERSION=true
        SFCGAL_VERSION=latest
      else
        DEVEL_VERSION=false
        SFCGAL_VERSION="${CI_COMMIT_TAG#v}"
      fi
      ./ci/build-macos-wheel.sh "${PYTHON_VERSION}" "${DEVEL_VERSION}" "${CI_COMMIT_TIMESTAMP}" "${SFCGAL_VERSION}"
  artifacts:
    paths:
      - dist_macos_$PYTHON_VERSION

build:documentation:
  stage: 📦 build
  image: ${PYTHON_DOCKER_IMAGE}
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "pysfcgal/*.py"
        - ".gitlab-ci.yml"
        - "requirements/documentation.txt"
        - "docs/docs/**/*.md"
      when: on_success
    - when: never
  before_script:
    - python -m pip install -U pip
    - python -m pip install -U -r requirements/documentation.txt
  script:
    - export PYTHONPATH=$(pwd)
    - cd docs && mkdocs build --verbose --strict
  artifacts:
    name: documentation
    expose_as: "built_documentation"
    paths:
      - docs/site
    when: always

# -- DEPLOYMENT JOBS ------------
pages:
  stage: 🚀 deploy
  only:
    refs:
      - master
  needs:
    - job: build:documentation
      artifacts: true
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir -p public
    - cp -rf docs/site/* public/
  artifacts:
    paths:
      - public

.common-deploy-wheel: &common-deploy-wheel
  stage: 🚀 deploy
  image: ${PYTHON_DOCKER_IMAGE}
  needs:
    - job: build:windows-osgeo4w-wheel
      artifacts: true
    - job: build:linux-wheel-python
      artifacts: true
    - job: build:macos-wheel-python
      artifacts: true

deploy:pypi:
  <<: *common-deploy-wheel
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - ./ci/prepare-deploy.sh
    - twine upload --password ${PYPI_API_TOKEN} dist/*

deploy:registry:
  <<: *common-deploy-wheel
  rules:
    # on default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # on a tag
    - if: $CI_COMMIT_TAG
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
  script:
    - ./ci/prepare-deploy.sh
    - twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
