ARG DEVEL_DATE
ARG DEVEL_VERSION=true
ARG PYTHON_WHEEL_VERSION=3.14
ARG SFCGAL_REGISTRY=registry.gitlab.com/sfcgal/sfcgal
ARG SFCGAL_VERSION=latest

FROM ${SFCGAL_REGISTRY}:manylinux-${SFCGAL_VERSION}

# copy files
COPY setup.py README.md ci/increment_version.py ./
COPY ./pysfcgal ./pysfcgal

# Increase the dev version number to upload the wheel to gitlab package registry
ARG DEVEL_DATE
ARG DEVEL_VERSION
RUN if [ "$DEVEL_VERSION" = "true" ]; then python3 increment_version.py ${DEVEL_DATE}; fi

# generate the wheels
ARG PYTHON_WHEEL_VERSION
RUN PY_VER=$(echo "$PYTHON_WHEEL_VERSION" | tr -d '.') && \
    /opt/python/cp$PY_VER-cp$PY_VER/bin/python -m venv venv && \
    . venv/bin/activate && \
    pip install -U auditwheel build patchelf pip twine && \
    python -m build && \
    auditwheel repair dist/*.whl -w /dist_linux_$PYTHON_WHEEL_VERSION/ --plat manylinux_2_26_x86_64 && \
    twine check --strict /dist_linux_$PYTHON_WHEEL_VERSION/*
