site_name: PySFCGAL - Documentation
repo_name: "pysfcgal"
repo_url: "https://gitlab.com/sfcgal/pysfcgal/"

theme:
  name: materialx
  features:
    - navigation.hide
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
  logo: assets/img/sfcgal.png
  favicon: assets/img/sfcgal.png
  icon:
    repo: fontawesome/brands/gitlab
    tag:
      default: fontawesome/solid/tag
  palette:
     primary: custom
     accent: custom


markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ""
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ""

plugins:
- search
- macros:
        module_name: macros
- mkdocstrings:
    default_handler: python  # optional
    handlers:
      python:
        options:
          docstring_style: numpy

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Installation: build.md
  - Getting started: getting_started.md
  - API Reference: api.md
  - Cookbook: cookbook.md
